package:
  name: data_api
  version: "{{ load_setup_py_data().version }}"
  
source:
  path: ../

build:
  entry_points:
    - data_api = data_api.client:cli
    - data_api_resolve_pulse_id = data_api.client:cli_resolve_pulse_id
  noarch: python
  
requirements:
  build:
    - python
  run:
    - python
    - requests
    - pandas
    - h5py
    - pytz
    - numpy


about:
  home: https://git.psi.ch/sf_daq/data-api_python
  license: GPLv3
