package:
  name: data_api
  version: 0.6.8
  
source:
  path: ../

build:
  entry_points:
    - data_api = data_api.client:cli
    - data_api_resolve_pulse_id = data_api.client:cli_resolve_pulse_id
  no-arch: python
  
requirements:
  build:
    - python
  run:
    - python
    - requests
    - pandas
    - h5py
    - pytz
    - numpy


about:
  home: https://github.com/paulscherrerinstitute/data_api_python
  license: GPLv3
