package:
  name: data_api
  version: "{{ load_setup_py_data().version }}"
  
source:
  path: ../

build:
  entry_points:
    - data_api = data_api.client:cli
    - api3 = data_api3.cli:main
    - data_api_resolve_pulse_id = data_api.client:cli_resolve_pulse_id
  noarch: python
  
requirements:
  build:
    - python
  run:
    - python
    - requests
    - pandas
    - h5py
    - pytz
    - numpy


about:
  home: https://github.com/paulscherrerinstitute/data_api_python
  license: GPLv3
