package:
  name: data_api
  version: 0.1.5pre1
  
source:
  path: ../

requirements:
  build:
    - python
  run:
    - python
    - requests
    - pandas

about:
  home: https://git.psi.ch/sf_daq/data-api_python
  license: GPLv3
